### ISSUE TITLE
作者您好，为什么安装完成后打不开呀？显示loading界面后程序自动killed

### ISSUE THREAD

**Issue by ChenPussssa** [CheshireCC/faster-whisper-GUI#128]
电脑配置如下
![Uploading 微信图片_20240501203853.jpg…]()

**Comment by ChenPussssa** [comment]
![Uploading 微信图片_20240501204104.png…]()

**Comment by CheshireCC** [comment]
看看日志是否有输出

**Comment by DrKinGpinG** [comment]
Try to run as administrator. Worked for me this way

**Comment by sapere-aude-incipe** [comment]
What worked for me was to install version 0.7.2.

Version 0.7.6 failed to open, even when run as admin, on a fresh install of both Windows 11 and Windows 10.

For information, the log file is located in: C:\Program Files (x86)\FasterWhisperGUI

Here is the content of the log file when 0.7.6 failed to open:

Traceback (most recent call last):
  File "C:\PROGRA~2\FASTER~1\fasterwhispergui.py", line 67, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\__init__.py", line 1, in <module faster_whisper_GUI>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\PROGRA~2\FASTER~1\whisperx\__init__.py", line 1, in <module whisperx>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\PROGRA~2\FASTER~1\whisperx\transcribe.py", line 9, in <module whisperx.transcribe>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\PROGRA~2\FASTER~1\whisperx\alignment.py", line 11, in <module whisperx.alignment>
  File "C:\Program Files (x86)\FasterWhisperGUI\torchaudio\__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
  File "C:\Program Files (x86)\FasterWhisperGUI\torchaudio\_extension\__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "C:\Program Files (x86)\FasterWhisperGUI\torchaudio\_extension\utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "C:\Program Files (x86)\FasterWhisperGUI\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "C:\PROGRA~2\FASTER~1\ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Program Files (x86)\FasterWhisperGUI\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by CheshireCC** [comment]
Did this file exited? version 0.7.6

**Comment by CheshireCC** [comment]
Did this file exist? version 0.7.6

**Comment by whnet** [comment]
对的，我也是遇到这个问题，一模一样

**Comment by rikimtasu** [comment]
> Did this file exist? version 0.7.6

yes,similar problem still exist for 0.7.6

**Comment by CheshireCC** [comment]
> C:\Program Files (x86)\FasterWhisperGUI\torchaudio\lib\libtorchaudio.pyd

check for this file:
```
C:\Program Files (x86)\FasterWhisperGUI\torchaudio\lib\libtorchaudio.pyd
```
