### ISSUE TITLE
卡在转写阶段进行不下去了，不出字幕文件

### ISSUE THREAD

**Issue by 2306624180** [CheshireCC/faster-whisper-GUI#129]
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/72365562/6a778169-0bb0-4d66-bf65-54c99473d240)
一直卡在这个进度，我看别人一开始没一会就转写好了，我们用的也都是一个版本号也都是V3模型，到底问题出在哪啊？

**Comment by GillianJiao** [comment]
换显卡，最有效

**Comment by rainnylin** [comment]
同樣的問題
版本：0.7.6
log檔

redirect std output
vad_filter : False
Transcribes options:
    -audio : ['K:/Temp/davinciCache/20240509_01.mp3']
    -language : zh
    -task : False
    -beam_size : 5
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.8
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 2.4
    -log_prob_threshold : -1.0
    -no_speech_threshold : 0.6
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
create transcribe process with 1 workers
start transcribe process
Estimating duration from bitrate, this may be inaccurate
Traceback (most recent call last):
  File "C:\Apps\FASTER~1\faster_whisper_GUI\transcribe.py", line 359, in run
  File "C:\Apps\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "C:\Apps\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "C:\Apps\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "C:\Apps\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "C:\Apps\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "C:\Apps\FASTER~1\faster_whisper_GUI\transcribe.py", line 269, in transcribe_file
  File "C:\Apps\FASTER~1\faster_whisper\transcribe.py", line 518, in generate_segments
  File "C:\Apps\FASTER~1\faster_whisper\transcribe.py", line 808, in generate_with_fallback
RuntimeError: [json.exception.type_error.305] cannot use operator[] with a string argument with null
