### ISSUE TITLE
1.转写视频文件失败，只有音频文件可以  2.每弄一次就用1g左右空间，是缓存吗？删除哪些文件释放空间？

### ISSUE THREAD

**Issue by pimin12** [CheshireCC/faster-whisper-GUI#149]
除了开了下使用v3模型其他用的都是默认设置，下面是视频文件转录时的log
    -language : ja
    -task : False
    -beam_size : 5
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.0
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 2.4
    -log_prob_threshold : -1.0
    -no_speech_threshold : 0.6
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
    -max_new_tokens : None
    -chunk_length : 30.0
    -clip_mode : 0
    -clip_timestamps : 0
    -hallucination_silence_threshold : 0.5
    -hotwords : 
    -language_detection_threshold : None
    -language_detection_segments : 1
create transcribe process with 1 workers
start transcribe process
Traceback (most recent call last):
  File "D:\FASTER~1\faster_whisper_GUI\transcribe.py", line 371, in run
  File "D:\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "D:\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "D:\FASTER~1\faster_whisper_GUI\transcribe.py", line 281, in transcribe_file
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 1175, in restore_speech_timestamps
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 573, in generate_segments
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 824, in encode
ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead

**Comment by CheshireCC** [comment]
1. 文件拖拽一直是有的，但是管理员身份启动会不能使用这个功能，这是 Qt 的限制，如果非管理员模式不能启动的话，那么你需要重新安装到一个不需要管理员权限的硬盘上去，
2. 不清楚你说的是哪里的空间？
3. 你给出的错误日志里提到的这个错误是 `梅尔滤波器组大小` 参数错误造成的，通常情况下这个错误是由于 V3 模型参数设置错误造成的，模型加载页面确认你使用的 是不是 large-V3 模型，如果不是的话关掉这个选项

**Comment by pimin12** [comment]
> 1. 文件拖拽一直是有的，但是管理员身份启动会不能使用这个功能，这是 Qt 的限制，如果非管理员模式不能启动的话，那么你需要重新安装到一个不需要管理员权限的硬盘上去，
> 2. 不清楚你说的是哪里的空间？
> 3. 你给出的错误日志里提到的这个错误是 `梅尔滤波器组大小` 参数错误造成的，通常情况下这个错误是由于 V3 模型参数设置错误造成的，模型加载页面确认你使用的 是不是 large-V3 模型，如果不是的话关掉这个选项

2.就是硬盘里的空间

**Comment by CheshireCC** [comment]
> > 1. 文件拖拽一直是有的，但是管理员身份启动会不能使用这个功能，这是 Qt 的限制，如果非管理员模式不能启动的话，那么你需要重新安装到一个不需要管理员权限的硬盘上去，
> > 2. 不清楚你说的是哪里的空间？
> > 3. 你给出的错误日志里提到的这个错误是 `梅尔滤波器组大小` 参数错误造成的，通常情况下这个错误是由于 V3 模型参数设置错误造成的，模型加载页面确认你使用的 是不是 large-V3 模型，如果不是的话关掉这个选项
> 
> 2.就是硬盘里的空间

那个是处理音视频文件的过程中产生的文件吧，然后就是torch 不知道会不会产生缓存文件
