### ISSUE TITLE
人声分离报错

### ISSUE THREAD

**Issue by sunyi369** [CheshireCC/faster-whisper-GUI#173]
请教大佬 版本0.8.0
看了下日志 提示==========Speaker_Diarize==========

min_speaker: 1
max_speaker: 10
Traceback (most recent call last):
  File "C:\FW\FASTER~1\faster_whisper_GUI\whisper_x.py", line 102, in run
  File "C:\FW\FASTER~1\whisperx\audio.py", line 46, in load_audio
  File "C:\FW\FASTER~1\ffmpeg\_run.py", line 313, in run
  File "C:\FW\FASTER~1\ffmpeg\_run.py", line 284, in run_async
  File "C:\FW\FASTER~1\subprocess.py", line 971, in __init__
  File "C:\FW\FASTER~1\subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by CheshireCC** [comment]
安装 ffmpeg

**Comment by sunyi369** [comment]
> 安装 ffmpeg

感谢，可以用了
