### ISSUE TITLE
TypeError: `pad_width` must be of integral type.

### ISSUE THREAD

**Issue by 1574300748** [CheshireCC/faster-whisper-GUI#187]
模型可以正常加载,使用的是您提供的large2,一到开始处理就卡在这
![PixPin_2024-07-17_19-12-11](https://github.com/user-attachments/assets/dc522183-a97c-4883-9ce9-a21fbffad057)
`==========2024-07-17_19:08:02==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.5
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -window_size_samples      : 1024
    -speech_pad_ms            : 400
Transcribes options:
    -audio : ['E:/StudyData/python/music_to_word/video-subtitle-generator-main/video-subtitle-generator-main/test/SUWK-022.mp3']
    -language : None
    -task : True
    -beam_size : 5
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.0
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 1.4
    -log_prob_threshold : -10.0
    -no_speech_threshold : 0.9
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
    -max_new_tokens : None
    -chunk_length : 30.0
    -clip_mode : 0
    -clip_timestamps : 0
    -hallucination_silence_threshold : 0.5
    -hotwords : 
    -language_detection_threshold : None
    -language_detection_segments : 1
create transcribe process with 1 workers
start transcribe process
Traceback (most recent call last):
  File "E:\StudyData\python\music_to_word\faster-whisper-GUI-main\faster-whisper-GUI-main\faster_whisper_GUI\transcribe.py", line 368, in run
    for path, results in zip(files, results):
  File "D:\Sofware\miniconda3\envs\voice2srt\lib\concurrent\futures\_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "D:\Sofware\miniconda3\envs\voice2srt\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "D:\Sofware\miniconda3\envs\voice2srt\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "D:\Sofware\miniconda3\envs\voice2srt\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\StudyData\python\music_to_word\faster-whisper-GUI-main\faster-whisper-GUI-main\faster_whisper_GUI\transcribe.py", line 230, in transcribe_file
    segments, info = self.model.transcribe(
  File "D:\Sofware\miniconda3\envs\voice2srt\lib\site-packages\faster_whisper\transcribe.py", line 357, in transcribe
    features = self.feature_extractor(audio, chunk_length=chunk_length)
  File "D:\Sofware\miniconda3\envs\voice2srt\lib\site-packages\faster_whisper\feature_extractor.py", line 155, in __call__
    waveform = np.pad(waveform, [(0, self.n_samples)])
  File "D:\Sofware\miniconda3\envs\voice2srt\lib\site-packages\numpy\lib\arraypad.py", line 745, in pad
    raise TypeError('`pad_width` must be of integral type.')
TypeError: `pad_width` must be of integral type.
`

**Comment by GillianJiao** [comment]
确实有时候用v3翻译突然卡死就一直显示处理中，翻译好几次俄语都出现这种情况

**Comment by CheshireCC** [comment]
> 确实有时候用v3翻译突然卡死就一直显示处理中，翻译好几次俄语都出现这种情况

显存不足了

**Comment by CheshireCC** [comment]
> 模型可以正常加载,使用的是您提供的large2,一到开始处理就卡在这 ![PixPin_2024-07-17_19-12-11](https://private-user-images.githubusercontent.com/127085932/349476200-dc522183-a97c-4883-9ce9-a21fbffad057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzEwODgsIm5iZiI6MTcyMTIzMDc4OCwicGF0aCI6Ii8xMjcwODU5MzIvMzQ5NDc2MjAwLWRjNTIyMTgzLWE5N2MtNDg4My05Y2U5LWEyMWZiZmZhZDA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxNTM5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDRjMDZjNGUwZGU0MmQzNjM4ZTEzYjRmZmFiNmZjOWYyZjA0MjQ0ZTFkNjQ1ZTkzOGY2OWFmODA4NTEwOTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WmoyJq2hMYTJpiKBaDgJgoLOeYVqGLmhAqN3k1Fc70Q) `==========2024-07-17_19:08:02========== ==========Process==========
> 
> redirect std output vad_filter : True -threshold : 0.5 -min_speech_duration_ms : 250 -max_speech_duration_s : inf -min_silence_duration_ms : 2000 -window_size_samples : 1024 -speech_pad_ms : 400 Transcribes options: -audio : ['E:/StudyData/python/music_to_word/video-subtitle-generator-main/video-subtitle-generator-main/test/SUWK-022.mp3'] -language : None -task : True -beam_size : 5 -best_of : 5 -patience : 1.0 -length_penalty : 1.0 -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0] -compression_ratio_threshold : 1.4 -log_prob_threshold : -10.0 -no_speech_threshold : 0.9 -condition_on_previous_text : False -initial_prompt : None -prefix : None -suppress_blank : True -suppress_tokens : [-1] -without_timestamps : False -max_initial_timestamp : 1.0 -word_timestamps : False -prepend_punctuations : "'“¿([{- -append_punctuations : "'.。,，!！?？:：”)]}、 -repetition_penalty : 1.0 -no_repeat_ngram_size : 0 -prompt_reset_on_temperature : 0.5 -max_new_tokens : None -chunk_length : 30.0 -clip_mode : 0 -clip_timestamps : 0 -hallucination_silence_threshold : 0.5 -hotwords : -language_detection_threshold : None -language_detection_segments : 1 create transcribe process with 1 workers start transcribe process Traceback (most recent call last): File "E:\StudyData\python\music_to_word\faster-whisper-GUI-main\faster-whisper-GUI-main\faster_whisper_GUI\transcribe.py", line 368, in run for path, results in zip(files, results): File "D:\Sofware\miniconda3\envs\voice2srt\lib\concurrent\futures_base.py", line 608, in result_iterator yield fs.pop().result() File "D:\Sofware\miniconda3\envs\voice2srt\lib\concurrent\futures_base.py", line 445, in result return self.__get_result() File "D:\Sofware\miniconda3\envs\voice2srt\lib\concurrent\futures_base.py", line 390, in __get_result raise self._exception File "D:\Sofware\miniconda3\envs\voice2srt\lib\concurrent\futures\thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "E:\StudyData\python\music_to_word\faster-whisper-GUI-main\faster-whisper-GUI-main\faster_whisper_GUI\transcribe.py", line 230, in transcribe_file segments, info = self.model.transcribe( File "D:\Sofware\miniconda3\envs\voice2srt\lib\site-packages\faster_whisper\transcribe.py", line 357, in transcribe features = self.feature_extractor(audio, chunk_length=chunk_length) File "D:\Sofware\miniconda3\envs\voice2srt\lib\site-packages\faster_whisper\feature_extractor.py", line 155, in **call** waveform = np.pad(waveform, [(0, self.n_samples)]) File "D:\Sofware\miniconda3\envs\voice2srt\lib\site-packages\numpy\lib\arraypad.py", line 745, in pad raise TypeError('`pad_width` must be of integral type.') TypeError: `pad_width` must be of integral type. `

源代码调试的吗？
