### ISSUE TITLE
whisperx这个保错是什么原因呢？

### ISSUE THREAD

**Issue by xlndql** [CheshireCC/faster-whisper-GUI#191]
==========2024-07-23_14:16:55==========
==========Speaker_Diarize==========

min_speaker: 1
max_speaker: 6
Traceback (most recent call last):
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\whisper_x.py", line 102, in run
  File "C:\PROGRA~2\FASTER~1\whisperx\audio.py", line 46, in load_audio
  File "C:\PROGRA~2\FASTER~1\ffmpeg\_run.py", line 313, in run
  File "C:\PROGRA~2\FASTER~1\ffmpeg\_run.py", line 284, in run_async
  File "C:\PROGRA~2\FASTER~1\subprocess.py", line 971, in __init__
  File "C:\PROGRA~2\FASTER~1\subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by xlndql** [comment]
0.8.0版本

**Comment by xlndql** [comment]
已解决
