### ISSUE TITLE
转录直接报错

### ISSUE THREAD

**Issue by lqisa** [CheshireCC/faster-whisper-GUI#200]
日志如下，运行即报错  看着是个JSON依赖报错
尝试过更换其他文件一样报错

```
redirect std output
vad_filter : True
    -threshold                : 0.5
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -window_size_samples      : 1024
    -speech_pad_ms            : 400
Transcribes options:
    -audio : ['D:/Documents/Downloads/カルタグラオリジナルサウンドトラック 「Manie -Rebirth-」/01_46_孤独の海.flac']
    -language : ja
    -task : False
    -beam_size : 5
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.0
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 2.4
    -log_prob_threshold : -1.0
    -no_speech_threshold : 0.6
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
    -max_new_tokens : None
    -chunk_length : 30.0
    -clip_mode : 0
    -clip_timestamps : 0
    -hallucination_silence_threshold : 0.5
    -hotwords : 
    -language_detection_threshold : None
    -language_detection_segments : 1
create transcribe process with 4 workers
start transcribe process
Traceback (most recent call last):
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 371, in run
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\_base.py", line 458, in result
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\thread.py", line 58, in run
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 281, in transcribe_file
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper\transcribe.py", line 1175, in restore_speech_timestamps
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper\transcribe.py", line 580, in generate_segments
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper\transcribe.py", line 870, in generate_with_fallback
RuntimeError: [json.exception.type_error.305] cannot use operator[] with a string argument with null
```

**Comment by hs012006023323** [comment]
我也出现同样的报错信息，请问问题解决了吗，怎么解决的呢

**Comment by CheshireCC** [comment]
这是哪个模型？会不会是模型文件缺失？

**Comment by lqisa** [comment]
> 我也出现同样的报错信息，请问问题解决了吗，怎么解决的呢

不知道啥问题 直接放弃了

**Comment by hs012006023323** [comment]
问题解决了，模型文件不全，要把模型相关的所有文件都放进model文件夹里

**Comment by CheshireCC** [comment]
> 问题解决了，模型文件不全，要把模型相关的所有文件都放进model文件夹里

😁
