### ISSUE TITLE
转录过程中报错missing key frame while searching for timestamp:1000

### ISSUE THREAD

**Issue by ForLuna1998** [CheshireCC/faster-whisper-GUI#201]
日志如下
Load over
C:/Users/Long'Min/Desktop/yd/fasterwhispergui/whisper-large-v3-float32
max_length:             448
num_samples_per_token:  320
time_precision:  0.02
tokens_per_second:  50
input_stride:  2
st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.

==========2024-08-06_15:11:32==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.5
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -window_size_samples      : 1024
    -speech_pad_ms            : 400
Traceback (most recent call last):
  File "D:\faster whisper\FasterWhisperGUI\faster_whisper_GUI\mainWindows.py", line 287, in onButtonProcessClicked
  File "D:\faster whisper\FasterWhisperGUI\faster_whisper_GUI\mainWindows.py", line 391, in transcribeProcess
  File "D:\faster whisper\FasterWhisperGUI\faster_whisper_GUI\mainWindows.py", line 758, in getParamTranscribe
ValueError: could not convert string to float: ''

**Comment by CheshireCC** [comment]
最晚初始时间戳 设错了吧
