### ISSUE TITLE
说话人分离功能报错

### ISSUE THREAD

**Issue by lvhengxin** [CheshireCC/faster-whisper-GUI#210]
日志
==========2024-08-20_22:20:25==========
==========Speaker_Diarize==========

min_speaker: 0
max_speaker: 6
Traceback (most recent call last):
  File "F:\FASTER~1\faster_whisper_GUI\whisper_x.py", line 102, in run
  File "F:\FASTER~1\whisperx\audio.py", line 53, in load_audio
ValueError: buffer size must be a multiple of element size

这个是什么原因可以解答下吗，感谢！

**Comment by UMRcoding** [comment]
需要有ffmpeg全局环境。
