### ISSUE TITLE
0.8.1爆显存，0.8.0没爆过，请教哪里的问题？

### ISSUE THREAD

**Issue by etkane** [CheshireCC/faster-whisper-GUI#225]
0.8.1已尝试了各种组合，看日志应该是爆显存。0.8.0版本从来没爆过，不知道哪里出了问题，今天刚升级。
日志如下：

==========2024-09-18_20:43:30==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.2
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -speech_pad_ms            : 800
Transcribes options:
    -audio : ['C:/Users/bican/Desktop/temp/去电_安诚保险_95544_202409141931.m4a']
    -language : zh
    -task : False
    -beam_size : 1
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.0
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 1.4
    -log_prob_threshold : -10.0
    -no_speech_threshold : 0.9
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : True
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
    -max_new_tokens : None
    -chunk_length : 30.0
    -clip_mode : 0
    -clip_timestamps : 0
    -hallucination_silence_threshold : 0.5
    -hotwords : 
    -language_detection_threshold : None
    -language_detection_segments : 1
create transcribe process with 1 workers
start transcribe process
Multiple frames in a packet.
Multiple frames in a packet.
Traceback (most recent call last):
  File "D:\PROGRA~2\FASTER~1\faster_whisper_GUI\transcribe.py", line 369, in run
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "D:\PROGRA~2\FASTER~1\faster_whisper_GUI\transcribe.py", line 279, in transcribe_file
  File "D:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 1189, in restore_speech_timestamps
  File "D:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 594, in generate_segments
  File "D:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 884, in generate_with_fallback
RuntimeError: CUDA failed with error out of memory

**Comment by etkane** [comment]
补充，显卡是4060 ，用CPU结果还是提示RuntimeError: CUDA failed with error out of memory，很奇怪，我是先直接安装了新版本，然后删除，重新安装了新版本，安装前没有仔细看说明，需要删除老版本。。。不知是否与此有关。

**Comment by etkane** [comment]
我删除了0.8.1，改回0.8.0版本，一切正常了。不知道问题出在哪里。。

**Comment by lowy-git** [comment]
同爆显存的路过
万幸0.80还没删

faster_whisper_GUI: 0.8.1
==========2024-09-19_14:33:49==========
==========Start==========

current computer language region-format: zh_CN
language: zh

==========2024-09-19_14:34:30==========
==========LoadModel==========

    -model_size_or_path: D:/Download/Install Backup/AI/whisper-large-v3-float32
    -device: cuda
    -device_index: 0
    -compute_type: float32
    -cpu_threads: 4
    -num_workers: 1
    -download_root: C:/Users/lowy/.cache/huggingface/hub
    -local_files_only: False
    -use_v3_model: True

Load over
D:/Download/Install Backup/AI/whisper-large-v3-float32
max_length:             448
num_samples_per_token:  320
time_precision:  0.02
tokens_per_second:  50
input_stride:  2

[Using V3 model, modify  number of mel-filters to 128]

==========2024-09-19_14:36:12==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.2
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -speech_pad_ms            : 800
Transcribes options:
    -audio : ['D:/Use now/LEL-Downloader/Download/中国大学/海上货物运输_大连海事大学/{1}--课程/{2}--第二章 包装危险货物运输/{1}--2.1 包装危险货物分类及危险性/[2.1.2]--2.1.2 第六类至第九类.mp4']
    -language : zh
    -task : False
    -beam_size : 1
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.0
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 1.4
    -log_prob_threshold : -10.0
    -no_speech_threshold : 0.9
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
    -max_new_tokens : None
    -chunk_length : 30.0
    -clip_mode : 0
    -clip_timestamps : 0
    -hallucination_silence_threshold : 0.5
    -hotwords : 
    -language_detection_threshold : None
    -language_detection_segments : 1
create transcribe process with 1 workers
start transcribe process
Traceback (most recent call last):
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\transcribe.py", line 369, in run
  File "C:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "C:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "C:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "C:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "C:\PROGRA~2\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\transcribe.py", line 279, in transcribe_file
  File "C:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 1189, in restore_speech_timestamps
  File "C:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 594, in generate_segments
  File "C:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 884, in generate_with_fallback
RuntimeError: CUDA failed with error out of memory
