### ISSUE TITLE
提示RuntimeError: CUDA failed with error no CUDA-capable device is detected，但是我有显卡

### ISSUE THREAD

**Issue by pkr5277** [CheshireCC/faster-whisper-GUI#23]
==========2023-10-31_16:58:12==========
==========LoadModel==========

model_size_or_path: Z:/Program Files/FasterWhisperGUI/models/faster-whisper/whisper-large-v2-ct2-32
device: cuda
device_index: 0
compute_type: float32
cpu_threads: 4
num_workers: 1
download_root: C:/Users/PKR/.cache/huggingface/hub
local_files_only: True
Exception in thread Thread-1 (go):
Traceback (most recent call last):
  File "Z:\Program Files\FasterWhisperGUI\threading.py", line 1016, in _bootstrap_inner
  File "Z:\Program Files\FasterWhisperGUI\threading.py", line 953, in run
  File "Z:\Program Files\FasterWhisperGUI\faster_whisper_GUI\mainWindows.py", line 197, in go
  File "Z:\Program Files\FasterWhisperGUI\faster_whisper_GUI\modelLoad.py", line 39, in loadModel
  File "Z:\Program Files\FasterWhisperGUI\threading.py", line 953, in run
  File "Z:\Program Files\FasterWhisperGUI\faster_whisper_GUI\modelLoad.py", line 22, in go
  File "Z:\Program Files\FasterWhisperGUI\faster_whisper\transcribe.py", line 128, in __init__
RuntimeError: CUDA failed with error no CUDA-capable device is detected

提示找不到cuda设备，但是我本地环境是有的，而且我自己用pycharm使用fast-whisper项目是可以提取的，如图，通过torch是可以打印设备的，请问一下这个项目的python用的是我本机的还是项目自带的？我本地环境是torch2.1.0+cuda12.1
<img width="738" alt="image" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/38154917/037ff54b-8ed0-4449-b37e-3a2fc631c5b5">

**Comment by pkr5277** [comment]
<img width="629" alt="image" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/38154917/dd9eef1f-c50d-4307-be89-7f2b75fb87a9">
我本地有很多版本的cuda，怎么能让他去找对应的版本呢？

**Comment by CheshireCC** [comment]
这个软件的 CUDA 环境不需要你本地配置，因为环境自带了，你本地的 CUDA 它不会用的
早期很多用户都不能正确配置 CUDA 所以我选择了将 CUDA 一并打包进安装包，后来使用 GPU 版本的 Torch 就不再自行打包 CUDA 了，因为 torch 不同版本需要对应的 CUDA 支持，所以为了保证稳定性，就使用了它本身的 CUDA 文件

**Comment by CheshireCC** [comment]
时间过久的 issue ，我将要关闭它，需要其它讨论的请开启新 issue
