### ISSUE TITLE
软件启动时报错，log如下。

### ISSUE THREAD

**Issue by AchillesL** [CheshireCC/faster-whisper-GUI#240]
Traceback (most recent call last):
  File "C:\PROGRA~2\FASTER~1\fasterwhispergui.py", line 67, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\__init__.py", line 1, in <module faster_whisper_GUI>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\PROGRA~2\FASTER~1\whisperx\__init__.py", line 1, in <module whisperx>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\PROGRA~2\FASTER~1\whisperx\transcribe.py", line 7, in <module whisperx.transcribe>
  File "C:\Program Files (x86)\FasterWhisperGUI\torch\__init__.py", line 130, in <module>
    raise err
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。 Error loading "C:\Program Files (x86)\FasterWhisperGUI\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.

**Comment by CheshireCC** [comment]
安装不全吧，丢东西了，卸载重装
