### ISSUE TITLE
(080)WhisperX对齐运行两次后选项卡丢失，文件无法保存

### ISSUE THREAD

**Issue by A2Sumie** [CheshireCC/faster-whisper-GUI#243]
081没有关于这个的changelog，姑且先报一下
我有一个3文件的广播素材，批量导入，whisper完成后在结果页用whisperX对齐，第一个选项卡点对齐后切换到第二个选项卡再点对齐，第一选项卡和第三选项卡消失，按保存是没有任何东西被保存
作为参考我按了一下ctrl A，此时第一个选项卡是全选中，另两个都没任何被选中的
单文件的情况下也会出现按第二次whisperX对齐后选项卡消失，按保存也没有文件被保存的情况

**Comment by CheshireCC** [comment]
whisperX 需要科学上网

**Comment by A2Sumie** [comment]
> whisperX 需要科学上网

本就在海外

**Comment by CheshireCC** [comment]
> > whisperX 需要科学上网
> 
> 本就在海外

whisperX失败的时候看看日志嘛

**Comment by A2Sumie** [comment]
```
  [717.28s --> 718.58s] ご視聴ありがとうございました
UPdata DataModel
tab_E:/Downloads/3_p3_(vocals).flac
updata table:E:/Downloads/3_p3_(vocals).flac
tab_E:/Downloads/2_sr135p2str_(vocals).flac
updata table:E:/Downloads/2_p2_(vocals).flac
tab_E:/Downloads/1_p1_(vocals).flac
updata table:E:/Downloads/1_p1_(vocals).flac

==========2024-10-21_00:19:27==========
==========TimeStample_Alignment==========


TimeStample alignment
transform transcript result...
process audio...
load wav2vec2 model...
--- Logging error ---
Traceback (most recent call last):
  File "E:\FastWhisper080\FasterWhisperGUI\logging\__init__.py", line 1103, in emit
ValueError: I/O operation on closed file.
Call stack:
  File "E:\FastWhisper080\FasterWhisperGUI\faster_whisper_GUI\whisper_x.py", line 71, in run
  File "E:\FastWhisper080\FasterWhisperGUI\whisperx\alignment.py", line 79, in load_align_model
  File "E:\FastWhisper080\FasterWhisperGUI\transformers\modeling_utils.py", line 3187, in from_pretrained
    ) = cls._load_pretrained_model(
  File "E:\FastWhisper080\FasterWhisperGUI\transformers\modeling_utils.py", line 3645, in _load_pretrained_model
    warner(
Message: "Some weights of the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-japanese were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_v', 'wav2vec2.encoder.pos_conv_embed.conv.weight_g']\n- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).\n- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model)."
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "E:\FastWhisper080\FasterWhisperGUI\logging\__init__.py", line 1103, in emit
ValueError: I/O operation on closed file.
Call stack:
  File "E:\FastWhisper080\FasterWhisperGUI\faster_whisper_GUI\whisper_x.py", line 71, in run
  File "E:\FastWhisper080\FasterWhisperGUI\whisperx\alignment.py", line 79, in load_align_model
  File "E:\FastWhisper080\FasterWhisperGUI\transformers\modeling_utils.py", line 3187, in from_pretrained
    ) = cls._load_pretrained_model(
  File "E:\FastWhisper080\FasterWhisperGUI\transformers\modeling_utils.py", line 3657, in _load_pretrained_model
    logger.warning(
Message: "Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-japanese and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0']\nYou should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference."
Arguments: ()
start alignment...
alignment Error
Error: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size
UPdata DataModel

==========OutputSubtitleFiles==========

【Over】

==========2024-10-21_00:19:57==========
==========deleteTable==========

removeTab: tab_E:/Downloads/2_p2_(vocals).flac
removeTable:tab_E:/Downloads/3_p3_(vocals).flac
len_DataModel:3
    E:/Downloads/3_p3_(vocals).flac
    E:/Downloads/2_p2_(vocals).flac
    E:/Downloads/1_p1_(vocals).flac
data to delete: tab_E:/Downloads/2_p2_(vocals).flac
key: E:/Downloads/2_p2_(vocals).flac
len_DataModel_after_pop:2
len_result: 0
len_result: 3
len_result: 0
len_current_result_after_pop: 0
len_result_faster_whisper_after_pop: 2
len_result_whisperX_alignment_after_pop: 0

```

**Comment by CheshireCC** [comment]
好的，我随后检查

**Comment by CheshireCC** [comment]
wshiperX 的 bug 已经修复
