### ISSUE TITLE
模型无法加载，不管是本地的还是在线的，都加载不出来，显卡看了下都是更新到最新了

### ISSUE THREAD

**Issue by RAYaaaaaaaaaaaaa** [CheshireCC/faster-whisper-GUI#250]
![Uploading 企业微信截图_20241122173816.png…]()

**Comment by RAYaaaaaaaaaaaaa** [comment]
<img width="624" alt="企业微信截图_20241122173816" src="https://github.com/user-attachments/assets/ac83dc9f-2749-49c2-8813-a0d698eb9d34">

**Comment by RAYaaaaaaaaaaaaa** [comment]
求求大佬回复

**Comment by CheshireCC** [comment]
看看日志

**Comment by RukaRozenE** [comment]
遇到了同样的问题，是下载的模型缺少model.bin文件导致的。
```
==========2024-12-19_16:47:47==========
==========LoadModel==========

    -model_size_or_path: G:/fast_whisper_model/models--Systran--faster-whisper-large-v3/snapshots/edaa852ec7e145841d8ffdb056a99866b5f0a478
    -device: cuda
    -device_index: 0
    -compute_type: float32
    -cpu_threads: 4
    -num_workers: 1
    -download_root: G:/fast_whisper_model
    -local_files_only: False
    -use_v3_model: True
Traceback (most recent call last):
  File "G:\FAST_W~1\faster_whisper_GUI\modelLoad.py", line 41, in run
  File "G:\FAST_W~1\faster_whisper_GUI\modelLoad.py", line 80, in loadModel
  File "G:\FAST_W~1\faster_whisper\transcribe.py", line 634, in __init__
RuntimeError: Unable to open file 'model.bin' in model 'G:/fast_whisper_model/models--Systran--faster-whisper-large-v3/snapshots/edaa852ec7e145841d8ffdb056a99866b5f0a478'

==========2024-12-19_16:47:50==========
==========Exit==========


==========2024-12-19_16:47:50==========
==========SaveConfigFile==========

no temp files to clear
```
模型文件夹中只有如下四个文件。
```
config.json
preprocessor_config.json
tokenizer.json
vocabulary.json
```

**Comment by RAYaaaaaaaaaaaaa** [comment]
这可咋整，有办法解决吗？我还不知道去哪看日志

**Comment by CheshireCC** [comment]
> 这可咋整，有办法解决吗？我还不知道去哪看日志
模型没下载全的话，就去下载完全就行了啊，日志文件可以在左下角设置菜单里打开

**Comment by RAYaaaaaaaaaaaaa** [comment]
hugging face 里好像还不能单独点着下载

**Comment by CheshireCC** [comment]
> hugging face 里好像还不能单独点着下载

??
