### ISSUE TITLE
转写时报错

### ISSUE THREAD

**Issue by zgijn** [CheshireCC/faster-whisper-GUI#251]
你好，软件日志如下：
redirect std output
vad_filter : False
Transcribes options:
    -audio : ['C:/Users/lkjhg/Desktop/111.mp3']
    -language : zh
    -task : False
    -beam_size : 5
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.0
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 2.4
    -log_prob_threshold : -1.0
    -no_speech_threshold : 0.6
    -condition_on_previous_text : True
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
    -max_new_tokens : None
    -chunk_length : 30.0
    -clip_mode : 2
    -clip_timestamps : []
    -hallucination_silence_threshold : 0.5
    -hotwords : 
    -language_detection_threshold : None
    -language_detection_segments : 1
create transcribe process with 1 workers
start transcribe process
Traceback (most recent call last):
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 371, in run
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\_base.py", line 458, in result
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\Program Files (x86)\FasterWhisperGUI\concurrent\futures\thread.py", line 58, in run
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 281, in transcribe_file
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper\transcribe.py", line 580, in generate_segments
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper\transcribe.py", line 870, in generate_with_fallback
RuntimeError: [json.exception.type_error.305] cannot use operator[] with a string argument with null

**Comment by zgijn** [comment]
使用的是0.8.0版本

**Comment by CheshireCC** [comment]
哪个模型？

**Comment by hs012006023323** [comment]
我也出现同样的报错信息，请问问题解决了吗，怎么解决的呢
