### ISSUE TITLE
RuntimeError: [json.exception.type_error.305] cannot use operator[] with a string argument with null

### ISSUE THREAD

**Issue by HotcatX** [CheshireCC/faster-whisper-GUI#26]
Traceback (most recent call last):
  File "D:\P\FASTER~1\faster_whisper_GUI\transcribe.py", line 333, in run
  File "D:\P\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\P\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\P\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "D:\P\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\P\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "D:\P\FASTER~1\faster_whisper_GUI\transcribe.py", line 207, in transcribe_file
  File "D:\P\FASTER~1\faster_whisper\transcribe.py", line 311, in transcribe
RuntimeError: [json.exception.type_error.305] cannot use operator[] with a string argument with null
Demucs可以正常使用。其他报错，使用模型是largev2

**Comment by CheshireCC** [comment]
请尝试手动选择音频所使用的语言，然后进行转写

**Comment by boomho** [comment]
**同样的问题，前台显示如下**

current task: D:/encore/xxxxl.mp4
  尝试解析文件
开始处理音频...
  Detected language [Korean] with probability [100.00%]
  Audio duration     —— [00:26:21.0467] 
  after VAD duration —— [00:19:00.704]
Transcription for xxxxl.mp4

**原本是直接卡在“开始处理音频..”，手动选择语言之后卡在了“Transcription for xxxxl.mp4”
log显示如下：**

==========2023-11-10_16:10:02==========
==========Process==========

Traceback (most recent call last):
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 333, in run
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\_base.py", line 458, in result
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\thread.py", line 58, in run
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 247, in transcribe_file
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper\transcribe.py", line 922, in restore_speech_timestamps
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper\transcribe.py", line 433, in generate_segments
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper\transcribe.py", line 641, in generate_with_fallback
RuntimeError: [json.exception.type_error.305] cannot use operator[] with a string argument with null

**使用的模型为https://huggingface.co/arc-r/faster-whisper-large-v2-Ko，参数只调整了输出为srt以及语言为ko，其他均为默认。**

**Comment by HotcatX** [comment]
> 请尝试手动选择音频所使用的语言，然后进行转写

我猜是环境冲突的问题，把系统环境变量里anaconda路径删了还真就正常了，楼上那位跟我问题一样的可以尝试一下。
现在每次用得删变量，不知道是哪里冲突了，习惯用虚拟环境
附上我的PATH：E:\anaconda3;E:\anaconda3\Library\mingw-w64\bin;E:\anaconda3\Library\usr\bin;E:\anaconda3\Library\bin;E:\anaconda3\Scripts;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;

**Comment by boomho** [comment]
卸载了anaconda，然后还原了系统环境变量里的Path为系统默认值（仅%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;）。但依然显示一样的报错，log跟上次一样，具体如下：

==========2023-11-12_02:58:28==========
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
language: zh_CN

==========2023-11-12_02:59:08==========
==========LoadModel==========

model_size_or_path: D:/WhisperCache/fasterwhisperlargev2Ko
device: cuda
device_index: 0
compute_type: int8
cpu_threads: 4
num_workers: 1
download_root: C:/Users/A/.cache/huggingface/hub
local_files_only: True

Load over
D:/WhisperCache/fasterwhisperlargev2Ko
max_length:             448
num_samples_per_token:  320
time_precision:  0.02
tokens_per_second:  50
input_stride:  2

==========2023-11-12_03:00:04==========
==========Process==========

Traceback (most recent call last):
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 333, in run
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\_base.py", line 458, in result
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\PROGRA~1\FasterWhisperGUI\concurrent\futures\thread.py", line 58, in run
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 247, in transcribe_file
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper\transcribe.py", line 922, in restore_speech_timestamps
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper\transcribe.py", line 433, in generate_segments
  File "D:\PROGRA~1\FasterWhisperGUI\faster_whisper\transcribe.py", line 641, in generate_with_fallback
RuntimeError: [json.exception.type_error.305] cannot use operator[] with a string argument with null

**Comment by CheshireCC** [comment]
链接：https://pan.baidu.com/s/1wQT2_941VhxxG53igKpeGw?pwd=2n9l 
提取码：2n9l 
--来自百度网盘超级会员V9的分享

试试其他模型？

**Comment by CheshireCC** [comment]
> > 请尝试手动选择音频所使用的语言，然后进行转写
> 
> 我猜是环境冲突的问题，把系统环境变量里anaconda路径删了还真就正常了，楼上那位跟我问题一样的可以尝试一下。 现在每次用得删变量，不知道是哪里冲突了，习惯用虚拟环境 附上我的PATH：E:\anaconda3;E:\anaconda3\Library\mingw-w64\bin;E:\anaconda3\Library\usr\bin;E:\anaconda3\Library\bin;E:\anaconda3\Scripts;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;

我自己也有安装Anoconda 并且也添加了环境变量，但是我没有发现过类似的情况，还需要观察观察😲

**Comment by boomho** [comment]
> 链接：https://pan.baidu.com/s/1wQT2_941VhxxG53igKpeGw?pwd=2n9l 提取码：2n9l --来自百度网盘超级会员V9的分享
> 
> 试试其他模型？

更换模型后可以正常转写了！看来我之前下的模型也有点问题。不过我在上一次卸载anaconda和更改环境变量后没有再重新安装anaconda和更改环境变量了，不知道这是不是也是个变量，供你参考。

**Comment by CheshireCC** [comment]
> 换模型后可以正常转写了！看来我之前下的模型也有点问题。不过我在上一次卸载anaconda和更改环境变量后没有再重新安装anaconda和更改环境变量了，不知道这是不是也是个变量，供你参考。

你检查一下你下载的模型内容是否完整，应该有的配置文件是否齐全，这几天我的机场故障了，没法下载 你的那个模型做测试

**Comment by boomho** [comment]
> > 换模型后可以正常转写了！看来我之前下的模型也有点问题。不过我在上一次卸载anaconda和更改环境变量后没有再重新安装anaconda和更改环境变量了，不知道这是不是也是个变量，供你参考。
> 
> 你检查一下你下载的模型内容是否完整，应该有的配置文件是否齐全，这几天我的机场故障了，没法下载 你的那个模型做测试

这个确实是我犯了个低级错误，我是从huggingface的files页面直接一个一个文件下载后一起拖进文件夹的，但是拖的时候没注意除模型外的文件都被变成了txt格式，导致模型无法正常使用（没改之前也可以成功加载，所以我迟迟没发现文件拓展名不对的问题）。把拓展名更改回去之后就可以正常使用了。

**Comment by CheshireCC** [comment]
好的，现在我将关闭该 issue，如果有新的问题请打开新的 issue 进行询问
