### ISSUE TITLE
把我桌面的东西全删了

### ISSUE THREAD

**Issue by arrrr2** [CheshireCC/faster-whisper-GUI#29]
下载并转换模型里面，因为想看看转换出啥所以选的桌面，结果转着转着报错，桌面的东西全没了
有点难绷

下面是log，想搜搜是不是调用了什么rm，果然有
model_size_or_path: tiny
device: cuda
device_index: 0
compute_type: float32
cpu_threads: 4
num_workers: 1
download_root: C:/Users/arr2/.cache/huggingface/hub
local_files_only: True
Exception in thread Thread-34 (go):
Traceback (most recent call last):
  File "C:\PROGRA~2\FASTER~1\threading.py", line 1016, in _bootstrap_inner
  File "C:\PROGRA~2\FASTER~1\threading.py", line 953, in run
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\mainWindows.py", line 197, in go
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\modelLoad.py", line 39, in loadModel
  File "C:\PROGRA~2\FASTER~1\threading.py", line 953, in run
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\modelLoad.py", line 22, in go
  File "C:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 122, in __init__
  File "C:\PROGRA~2\FASTER~1\faster_whisper\utils.py", line 99, in download_model
  File "C:\Program Files (x86)\FasterWhisperGUI\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Program Files (x86)\FasterWhisperGUI\huggingface_hub\_snapshot_download.py", line 169, in snapshot_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/arr2/.cache/huggingface/hub\\models--guillaumekln--faster-whisper-tiny\\refs\\main'
....

Downloading (…)in/added_tokens.json: 100%|##########| 34.6k/34.6k [00:00<00:00, 111kB/s]
...
Downloading (…)cial_tokens_map.json:   0%|          | 0.00/2.08k [00:00<?, ?B/s]
Downloading (…)cial_tokens_map.json: 100%|##########| 2.08k/2.08k [00:00<?, ?B/s]
.Exception in thread .Thread-6 (go_2):
Traceback (most recent call last):
  File "C:\PROGRA~2\FASTER~1\threading.py", line 1016, in _bootstrap_inner
  File "C:\PROGRA~2\FASTER~1\threading.py", line 953, in run
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\convertModel.py", line 87, in go_2
  File "C:\PROGRA~2\FASTER~1\ctranslate2\converters\converter.py", line 102, in convert
  File "C:\PROGRA~2\FASTER~1\shutil.py", line 750, in rmtree
  File "C:\PROGRA~2\FASTER~1\shutil.py", line 624, in _rmtree_unsafe
  File "C:\PROGRA~2\FASTER~1\shutil.py", line 622, in _rmtree_unsafe
PermissionError: [WinError 5] 拒绝访问。: 'C:/Users/arr2/Desktop'

Over

**Comment by CheshireCC** [comment]
转换出的模型包含配置文件的话本身是多文件的，所以没有考虑直接放在根目录下的情况
另外转换功能用的太少，所以这个接口长时间没有维护了。。。

**Comment by CheshireCC** [comment]
暂时停用转换模型相关功能
