### ISSUE TITLE
加载模型报错

### ISSUE THREAD

**Issue by Jiang10086** [CheshireCC/faster-whisper-GUI#35]
报错 log：
`==========LoadModel==========

model_size_or_path: C:/Users/Extre/Downloads/model-large-v3
device: auto
device_index: 0
compute_type: float32
cpu_threads: 4
num_workers: 1
download_root: C:/Users/Extre/.cache/huggingface/hub
local_files_only: True
Exception in thread Thread-9 (go):
Traceback (most recent call last):
  File "C:\PROGRA~2\FASTER~1\threading.py", line 1016, in _bootstrap_inner
  File "C:\PROGRA~2\FASTER~1\threading.py", line 953, in run
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\mainWindows.py", line 200, in go
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\modelLoad.py", line 40, in loadModel
  File "C:\PROGRA~2\FASTER~1\threading.py", line 953, in run
  File "C:\PROGRA~2\FASTER~1\faster_whisper_GUI\modelLoad.py", line 22, in go
  File "C:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 128, in __init__
RuntimeError: Unable to open file 'model.bin' in model 'C:/Users/Extre/Downloads/model-large-v3'
`

模型是从 [https://huggingface.co/gradjitta/ct2-whisper-large-v3/tree/main](https://huggingface.co/gradjitta/ct2-whisper-large-v3/tree/main) 下载的，是在软件“模型参数-Local Model”那里加载的

其他信息：
- 系统版本：Windows 11 专业工作站版
- 软件版本：4.0.3
- 显卡：NVIDIA GeForce MX330，已安装 CUDA

**Comment by CheshireCC** [comment]
配置文件完整吗？如果完整还是不能加载的话试试这个：
链接：https://pan.baidu.com/s/1_kaG5qLqxWbMP729p6N5FQ?pwd=ebdh 
提取码：ebdh 
--来自百度网盘超级会员V9的分享

**Comment by CheshireCC** [comment]
另外由于 windows11 权限原因，您最好不要将文件放在需要高级权限的位置，比如 系统盘、不能由普通用户权限修改的文件夹等

**Comment by Jiang10086** [comment]
> 另外由于 windows11 权限原因，您最好不要将文件放在需要高级权限的位置，比如 系统盘、不能由普通用户权限修改的文件夹等

您说的文件是模型（model）文件吗？

**Comment by Jiang10086** [comment]
> 配置文件完整吗？如果完整还是不能加载的话试试这个： 链接：https://pan.baidu.com/s/1_kaG5qLqxWbMP729p6N5FQ?pwd=ebdh 提取码：ebdh --来自百度网盘超级会员V9的分享

原来除了 .bin 文件，其他几个小文件也要下载。我会再试试的

**Comment by CheshireCC** [comment]
> > 配置文件完整吗？如果完整还是不能加载的话试试这个： 链接：https://pan.baidu.com/s/1_kaG5qLqxWbMP729p6N5FQ?pwd=ebdh 提取码：ebdh --来自百度网盘超级会员V9的分享
> 
> 原来除了 .bin 文件，其他几个小文件也要下载。我会再试试的

是的，配置文件必须要有，否则就算能加载模型也会在运行语音识别的时候出错

**Comment by CheshireCC** [comment]
如果该问题已经解决，请关闭issue，如果没有解决可以继续讨论

**Comment by Jiang10086** [comment]
先关闭吧，我无法进行验证了。软件不知道为啥启动不了了，不好意思
