### ISSUE TITLE
视频会因为作者在其他帖子里说的问题报错,但是我按指示把视频转换成音频后显示RuntimeError: CUDA failed with error out of memory

### ISSUE THREAD

**Issue by sqsq37** [CheshireCC/faster-whisper-GUI#48]
==========2023-12-10_08:01:27==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.5
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -window_size_samples      : 1024
    -speech_pad_ms            : 400
Transcribes options:    -audio : ['D:/提取音频/BUENA-143 ☆高画質DVD-ROM☆F●O＠ジャッ●・ザ・リッパー.wav']    -language : ja    -task : False    -beam_size : 5    -best_of : 1    -patience : 1.0    -length_penalty : 1.0    -temperature : [0.0]    -compression_ratio_threshold : 2.4    -log_prob_threshold : -1.0    -no_speech_threshold : 0.6    -condition_on_previous_text : False    -initial_prompt : None    -prefix : None    -suppress_blank : True    -suppress_tokens : [-1]    -without_timestamps : False    -max_initial_timestamp : 1.0    -word_timestamps : True    -prepend_punctuations : "'“¿([{-    -append_punctuations : "'.。,，!！?？:：”)]}、    -repetition_penalty : 1.0    -no_repeat_ngram_size : 0    -prompt_reset_on_temperature : 0.5create transcribe process with 1 workersstart transcribe processTraceback (most recent call last):
  File "D:\FASTER~1\faster_whisper_GUI\transcribe.py", line 353, in run
  File "D:\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "D:\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "D:\FASTER~1\faster_whisper_GUI\transcribe.py", line 266, in transcribe_file
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 922, in restore_speech_timestamps
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 538, in generate_segments
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 765, in add_word_timestamps
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 875, in find_alignment
RuntimeError: CUDA failed with error out of memory

**Comment by sqsq37** [comment]
重装软件后又正常能用了了,估计是我之前强推太多次导致什么东西损坏了,没事了

**Comment by CheshireCC** [comment]
好的
