### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by DevrainW** [CheshireCC/faster-whisper-GUI#49]
Traceback (most recent call last):
  File "D:\ProgramAI\GUI\fasterwhispergui.py", line 9, in <module>
  File "D:\ProgramAI\GUI\faster_whisper_GUI\__init__.py", line 1, in <module faster_whisper_GUI>
  File "D:\ProgramAI\GUI\whisperx\__init__.py", line 1, in <module whisperx>
  File "D:\ProgramAI\GUI\whisperx\transcribe.py", line 6, in <module whisperx.transcribe>
ModuleNotFoundError: No module named 'numpy'

**Comment by CheshireCC** [comment]
源码运行需要检查你的环境
安装运行检查你的安装是否完整

**Comment by FreemanZ** [comment]
这是把patch包当本体了么，昨天我也遇到这个情况了，还说这玩意儿怎么这么小

**Comment by CheshireCC** [comment]
> 这是把patch包当本体了么，昨天我也遇到这个情况了，还说这玩意儿怎么这么小

这个算我的疏忽造成必须 patch，编译之前没注意到环境版本变了
