### ISSUE TITLE
无法批量转换

### ISSUE THREAD

**Issue by 1353604736** [CheshireCC/faster-whisper-GUI#56]
无法批量转换

**Comment by CheshireCC** [comment]
描述得不够清楚，
需要log文件信息，log文件可在设置页面打开

**Comment by 1353604736** [comment]
> 描述得不够清楚， 需要log文件信息，log文件可在设置页面打开

fasterwhispergui.log
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.

faster_whisper_GUI: 0.5.0
==========2023-12-31_16:37:39==========
==========Start==========

language: zh

==========2023-12-31_16:37:48==========
==========LoadModel==========

model_size_or_path: D:/Program Files (x86)/FasterWhisperGUI/huggingface/hub/faster-whisper-large-v3
device: cuda
device_index: 0
compute_type: float32
cpu_threads: 4
num_workers: 4
download_root: C:/Users/12059/.cache/huggingface/hub
local_files_only: False

Load over
D:/Program Files (x86)/FasterWhisperGUI/huggingface/hub/faster-whisper-large-v3
max_length:             448
num_samples_per_token:  320
time_precision:  0.02
tokens_per_second:  50
input_stride:  2

[Using V3 model, modify  number of mel-filters to 128]

==========2023-12-31_16:39:40==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.5
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -window_size_samples      : 1024
    -speech_pad_ms            : 400
Transcribes options:    -audio : ['F:/闪豆下载/抖音视频/皮先生/2022-02-2208_52_40多多视频带货玩法教程交流群.mp4', 'F:/闪豆下载/抖音视频/皮先生/2022-03-1723_55_57拼多多视频带货玩法交流群，多多视频带货教程怎么做？.mp4']    -language : zh    -task : False    -beam_size : 5    -best_of : 1    -patience : 1.0    -length_penalty : 1.0    -temperature : [0.0]    -compression_ratio_threshold : 2.4    -log_prob_threshold : -1.0    -no_speech_threshold : 0.6    -condition_on_previous_text : False    -initial_prompt : None    -prefix : None    -suppress_blank : True    -suppress_tokens : [-1]    -without_timestamps : False    -max_initial_timestamp : 1.0    -word_timestamps : False    -prepend_punctuations : "'“¿([{-    -append_punctuations : "'.。,，!！?？:：”)]}、    -repetition_penalty : 1.0    -no_repeat_ngram_size : 0    -prompt_reset_on_temperature : 0.5create transcribe process with 4 workersstart transcribe processF:/闪豆下载/抖音视频/皮先生/2022-02-2208_52_40多多视频带货玩法教程交流群.mp4 zh
len:0
F:/闪豆下载/抖音视频/皮先生/2022-03-1723_55_57拼多多视频带货玩法交流群，多多视频带货教程怎么做？.mp4 zh
len:8
len_segments_path_info_result: 2
Create Tables
len_model: 2

==========2023-12-31_16:41:15==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.5
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -window_size_samples      : 1024
    -speech_pad_ms            : 400
Transcribes options:    -audio : ['F:/闪豆下载/抖音视频/皮先生/2022-03-2923_26_04带货内部玩法交流群，每天数据都很平稳，欢迎来群交流！.mp4', 'F:/闪豆下载/抖音视频/皮先生/2022-07-1221_53_57#多多视频带货 #多多视频#带货 #好物 多多视频还能做吗？新手该怎么做？.mp4', 'F:/闪豆下载/抖音视频/皮先生/2022-07-1914_29_40多多视频新规则，认证原创银牌，没难度，秒过！.mp4', 'F:/闪豆下载/抖音视频/皮先生/2022-07-1915_39_35多多视频带货资格奖励怎么快速获得？.mp4', 'F:/闪豆下载/抖音视频/皮先生/2022-07-2111_36_15多多视频蓝海带货，原创银牌作者认证！.mp4', 'F:/闪豆下载/抖音视频/皮先生/2022-07-2122_43_50一天只花3块，你能做到吗？.mp4', 'F:/闪豆下载/抖音视频/皮先生/2022-02-2208_52_40多多视频带货玩法教程交流群.mp4', 'F:/闪豆下载/抖音视频/皮先生/2022-03-1723_55_57拼多多视频带货玩法交流群，多多视频带货教程怎么做？.mp4']    -language : zh    -task : False    -beam_size : 5    -best_of : 1    -patience : 1.0    -length_penalty : 1.0    -temperature : [0.0]    -compression_ratio_threshold : 2.4    -log_prob_threshold : -1.0    -no_speech_threshold : 0.6    -condition_on_previous_text : False    -initial_prompt : None    -prefix : None    -suppress_blank : True    -suppress_tokens : [-1]    -without_timestamps : False    -max_initial_timestamp : 1.0    -word_timestamps : False    -prepend_punctuations : "'“¿([{-    -append_punctuations : "'.。,，!！?？:：”)]}、    -repetition_penalty : 1.0    -no_repeat_ngram_size : 0    -prompt_reset_on_temperature : 0.5create transcribe process with 4 workersstart transcribe processTraceback (most recent call last):
  File "D:\PROGRA~2\FASTER~1\faster_whisper_GUI\transcribe.py", line 353, in run
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\PROGRA~2\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "D:\PROGRA~2\FASTER~1\faster_whisper_GUI\transcribe.py", line 266, in transcribe_file
  File "D:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 922, in restore_speech_timestamps
  File "D:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 433, in generate_segments
  File "D:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 641, in generate_with_fallback
RuntimeError: CUDA failed with error out of memory
============================================================================
faster_whisper.log
2023-12-31_16:39:40 - faster_whisper - INFO - Processing audio with duration 00:24.915
2023-12-31_16:39:40 - faster_whisper - INFO - Processing audio with duration 00:19.156
2023-12-31_16:39:41 - faster_whisper - INFO - VAD filter removed 00:00.000 of audio
2023-12-31_16:39:41 - faster_whisper - DEBUG - VAD filter kept the following audio segments: [00:00.000 -> 00:19.156]
2023-12-31_16:39:42 - faster_whisper - INFO - VAD filter removed 00:24.915 of audio
2023-12-31_16:39:42 - faster_whisper - DEBUG - VAD filter kept the following audio segments: 
2023-12-31_16:39:42 - faster_whisper - DEBUG - Processing segment at 00:00.000
2023-12-31_16:41:15 - faster_whisper - INFO - Processing audio with duration 00:07.941
2023-12-31_16:41:15 - faster_whisper - INFO - VAD filter removed 00:00.000 of audio
2023-12-31_16:41:15 - faster_whisper - DEBUG - VAD filter kept the following audio segments: [00:00.000 -> 00:07.941]
2023-12-31_16:41:15 - faster_whisper - INFO - Processing audio with duration 00:09.822
2023-12-31_16:41:15 - faster_whisper - INFO - VAD filter removed 00:00.000 of audio
2023-12-31_16:41:15 - faster_whisper - DEBUG - VAD filter kept the following audio segments: [00:00.000 -> 00:09.822]
2023-12-31_16:41:15 - faster_whisper - INFO - Processing audio with duration 00:18.413
2023-12-31_16:41:15 - faster_whisper - INFO - VAD filter removed 00:00.240 of audio
2023-12-31_16:41:15 - faster_whisper - DEBUG - VAD filter kept the following audio segments: [00:00.240 -> 00:18.413]
2023-12-31_16:41:15 - faster_whisper - DEBUG - Processing segment at 00:00.000
2023-12-31_16:41:16 - faster_whisper - DEBUG - Processing segment at 00:00.000
2023-12-31_16:41:16 - faster_whisper - DEBUG - Processing segment at 00:00.000
2023-12-31_16:41:16 - faster_whisper - INFO - Processing audio with duration 02:17.462
2023-12-31_16:41:16 - faster_whisper - INFO - VAD filter removed 00:00.000 of audio
2023-12-31_16:41:16 - faster_whisper - DEBUG - VAD filter kept the following audio segments: [00:00.000 -> 02:17.462]
2023-12-31_16:41:17 - faster_whisper - DEBUG - Processing segment at 00:00.000
2023-12-31_16:41:19 - faster_whisper - INFO - Processing audio with duration 00:09.636
2023-12-31_16:41:19 - faster_whisper - INFO - VAD filter removed 00:00.000 of audio
2023-12-31_16:41:19 - faster_whisper - DEBUG - VAD filter kept the following audio segments: [00:00.000 -> 00:09.636]
2023-12-31_16:41:19 - faster_whisper - DEBUG - Processing segment at 00:00.000
2023-12-31_16:41:19 - faster_whisper - INFO - Processing audio with duration 00:09.543
2023-12-31_16:41:19 - faster_whisper - INFO - VAD filter removed 00:00.000 of audio
2023-12-31_16:41:19 - faster_whisper - DEBUG - VAD filter kept the following audio segments: [00:00.000 -> 00:09.543]
2023-12-31_16:41:19 - faster_whisper - DEBUG - Processing segment at 00:00.000
2023-12-31_16:41:19 - faster_whisper - INFO - Processing audio with duration 00:24.915
2023-12-31_16:41:19 - faster_whisper - INFO - Processing audio with duration 00:19.156
2023-12-31_16:41:19 - faster_whisper - INFO - VAD filter removed 00:24.915 of audio
2023-12-31_16:41:19 - faster_whisper - DEBUG - VAD filter kept the following audio segments: 
2023-12-31_16:41:20 - faster_whisper - INFO - VAD filter removed 00:00.000 of audio
2023-12-31_16:41:20 - faster_whisper - DEBUG - VAD filter kept the following audio segments: [00:00.000 -> 00:19.156]
2023-12-31_16:41:20 - faster_whisper - DEBUG - Processing segment at 00:00.000

然后软件就一直显示音频处理正在处理中，GPU也一直没负载

**Comment by CheshireCC** [comment]
这个，显存不够使，溢出了
建议更换量化方式为 int8 或者 float16 ，但不是所有的显卡设备都支持 float16 所以直接 int8 吧
另外如果需要使用 whisperX 的话，可以尝试在转写完之后卸载掉 whisper 模型，释放显存

**Comment by 1353604736** [comment]
> 长时间没有回应，现在关闭该 issue

int8可以了，不过有一个问题，处理长音频比如6小时或更多，会爆内存，开始转写一段时间后内存暴涨到系统卡死
