### ISSUE TITLE
新版本翻译有tag数据的WAV文件会报错停止

### ISSUE THREAD

**Issue by sqsq37** [CheshireCC/faster-whisper-GUI#59]
新版本翻译有tag数据的WAV文件会报错停止
文件就是上次我发你那两个
create transcribe process with 2 workers
start transcribe process
Discarding ID3 tags because more suitable tags were found.
Discarding ID3 tags because more suitable tags were found.
Traceback (most recent call last):
  File "D:\FASTER~1\faster_whisper_GUI\transcribe.py", line 353, in run
  File "D:\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "D:\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "D:\FASTER~1\faster_whisper_GUI\transcribe.py", line 266, in transcribe_file
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 922, in restore_speech_timestamps
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 426, in generate_segments
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 610, in encode
ValueError: Invalid input features shape: expected an input with shape (1, 80, 3000), but got an input with shape (1, 128, 3000) instead

**Comment by sqsq37** [comment]
2024-01-01_22:34:45 - faster_whisper - DEBUG - Processing segment at 00:00.000
2024-01-01_22:35:30 - faster_whisper - DEBUG - Processing segment at 00:28.500

**Comment by CheshireCC** [comment]
这不是数据问题，是因为你没有使用 V3 模型但打开了相关选项造成的，不使用 V3 模型的时候不能开 V3 模型选项

**Comment by sqsq37** [comment]
看到了，原来更新后的V3选项是默认打开的，我还以为我老版本的设置都保留来着不开来着

**Comment by CheshireCC** [comment]
要保留设置你就自己备份一下配置文件嘛，也许下个版本应该给个手动备份、导入配置的功能

**Comment by sqsq37** [comment]
开始处理音频...
  Detected language [Japanese] with probability [100.00%]
  Audio duration     —— [00:29:37.2134] 
  after VAD duration —— [00:25:12.608]
Transcription for 01 Track01.wav
开始处理音频...
  Detected language [Japanese] with probability [100.00%]
  Audio duration     —— [00:29:04.600] 
  after VAD duration —— [00:23:28.000]
Transcription for 02 Track02.wav

新版本批量处理是先把VAD都提取完再提取字幕吗
这个情况我之前版本没见过，V3关了

**Comment by CheshireCC** [comment]
显存问题，显存爆炸了，显存不够的情况下在模型页面更改 量化类型（也就是计算精度） 直接改成 int8 吧

**Comment by sqsq37** [comment]
调成16还是爆了，这个会影响提取精度吗 ，老版本我都没管过这个怎么新版出事了

**Comment by sqsq37** [comment]
关闭卡拉OK级时间戳就行了，估计是这个功能太占用 显存了

**Comment by CheshireCC** [comment]
> 调成16还是爆了，这个会影响提取精度吗 ，老版本我都没管过这个怎么新版出事了

有一定的影响，但是不大

**Comment by CheshireCC** [comment]
> 关闭卡拉OK级时间戳就行了，估计是这个功能太占用 显存了

我这边打开了单词级时间戳，显存占用大概 7.6 GB， 8G 显存勉强撑住

**Comment by sqsq37** [comment]
> > 关闭卡拉OK级时间戳就行了，估计是这个功能太占用 显存了
> 
> 我这边打开了单词级时间戳，显存占用大概 7.6 GB， 8G 显存勉强撑住

怪事，我4070 12g一开就爆，不开完全没事 计算进度32

**Comment by CheshireCC** [comment]
> > > 关闭卡拉OK级时间戳就行了，估计是这个功能太占用 显存了
> > 
> > 
> > 我这边打开了单词级时间戳，显存占用大概 7.6 GB， 8G 显存勉强撑住
> 
> 怪事，我4070 12g一开就爆，不开完全没事 计算进度32

我也是用 32 位模型的，你看一眼 任务管理器 ，你的可用显存还有 8GB 不？ 是不是开了别的什么软件很占显存？
