### ISSUE TITLE
FLAC格式的音频不会生成到output的数据

### ISSUE THREAD

**Issue by sqsq37** [CheshireCC/faster-whisper-GUI#61]
FLAC格式的音频不会生成到output的数据并提示跳转
只能手动去临时文件夹复制粘贴SRT

write over | ./temp/Track 01.srt
save temp file: ./temp/Track 01.srt

【Over】

**Comment by sqsq37** [comment]
又翻了一个，又会跳转了，看来是概率触发的，我试试复现

**Comment by CheshireCC** [comment]
检查 log 文件

**Comment by sqsq37** [comment]
len_words: 0
[1784.42s --> 1793.82] | 能让我做这种事的女孩子只有我，绝对不会放手吗？
len_words: 0
[1796.18s --> 1809.1] | 我好开心，请好好把这份感情刻在屁眼上哦，男朋友
len_words: 0
len_segments_path_info_result: 2
UPdata DataModel
Traceback (most recent call last):
  File "D:\FASTER~1\faster_whisper_GUI\mainWindows.py", line 581, in transcribeOver
  File "D:\FASTER~1\faster_whisper_GUI\mainWindows.py", line 522, in showResultInTable
  File "D:\FASTER~1\faster_whisper_GUI\mainWindows.py", line 508, in changeTableData
KeyError: 'G:/非DL音声/イチャラブご奉仕、スケべな時子は俺の便器彼女ドラマCD/Track 01.flac'

**Comment by sqsq37** [comment]
[3477.39s --> 3482.79] | 我不是说了我期待着吗
len_words: 0
[3482.79s --> 3491.13] | 所以请再次...用我的身体来让鸡鸡...变得舒服起来吧
len_words: 0
len_segments_path_info_result: 1
UPdata DataModel
Traceback (most recent call last):
  File "D:\FASTER~1\faster_whisper_GUI\mainWindows.py", line 581, in transcribeOver
  File "D:\FASTER~1\faster_whisper_GUI\mainWindows.py", line 522, in showResultInTable
  File "D:\FASTER~1\faster_whisper_GUI\mainWindows.py", line 508, in changeTableData
KeyError: 'G:/非DL音声/任務帰りに二穴中出しセックスドラマCD/Track 01.flac'

**Comment by CheshireCC** [comment]
我猜，因该是文件名里面那些奇奇怪怪的字符造成的

**Comment by sqsq37** [comment]
文件名是单纯的Track 01.flac啊，是指文件夹名字吗

**Comment by CheshireCC** [comment]
整个路径名都算

**Comment by CheshireCC** [comment]
用了你文件名之后，我这边转写完甚至卡住不能动弹

**Comment by sqsq37** [comment]
那估计是日文片假名的问题了，也不是啥大问题，老老实实多一步复制粘贴就行了

**Comment by CheshireCC** [comment]
不过也不是每一次都会，可能是和计算机环境有关系，我试了三次也只卡了一次

**Comment by CheshireCC** [comment]
另外你的两次 log 文件都显示 UPdata DataModel，说明之前已经有转写结果在了，你是不是重复转写或者在表格页面关闭过表格标签了？

**Comment by sqsq37** [comment]
> 另外你的两次 log 文件都显示 UPdata DataModel，说明之前已经有转写结果在了，你是不是重复转写或者在表格页面关闭过表格标签了？
这个系列的音声文件名都是Track xx.flac
之前转写的音声和后面的是同名，所以临时文件文件名是一样的

**Comment by CheshireCC** [comment]
那就是了，因为表格标签是靠文件名标识的，所以同名文件会冲突😑
这就很麻烦了，需要重构这部分逻辑
下个版本更新看看能不能有所改善吧

**Comment by CheshireCC** [comment]
0.5.7 已经修复
