### ISSUE TITLE
0.6模型加载失败，0.5.7正常使用

### ISSUE THREAD

**Issue by 1353604736** [CheshireCC/faster-whisper-GUI#93]
fasterwhispergui.log
【【【【【【【【【

The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.

faster_whisper_GUI: 0.6.0
==========2024-03-04_13:04:06==========
==========Start==========

language: zh

==========2024-03-04_13:04:19==========
==========LoadModel==========

    -model_size_or_path: D:/Program Files (x86)/FasterWhisperGUI/huggingface/hub/faster-whisper-large-v3
    -device: cuda
    -device_index: 0
    -compute_type: int8
    -cpu_threads: 4
    -num_workers: 1
    -download_root: D:/ProgramFiles(x86)/FasterWhisperGUI/cache
    -local_files_only: True
    -use_v3_model: True
Traceback (most recent call last):
  File "D:\PROGRA~2\FASTER~1\faster_whisper_GUI\modelLoad.py", line 41, in run
  File "D:\PROGRA~2\FASTER~1\faster_whisper_GUI\modelLoad.py", line 73, in loadModel
  File "D:\PROGRA~2\FASTER~1\faster_whisper\transcribe.py", line 133, in __init__
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

==========2024-03-04_13:04:53==========
==========Exit==========

==========2024-03-04_13:04:53==========
==========SaveConfigFile==========

no temp files to clear

】】】】】】】】】】

![微信截图_20240304130446](https://github.com/CheshireCC/faster-whisper-GUI/assets/12869582/6a3f18a3-b217-47c8-b4b8-bc4d6a3d1436)

**Comment by 1353604736** [comment]
> 更新驱动版本， 0.6.0 现在最高支持到 CUDA12.1 了

已解决，驱动更新就好了
