### ISSUE TITLE
0.6版本无法启动

### ISSUE THREAD

**Issue by Xuwznln** [CheshireCC/faster-whisper-GUI#94]
刚升级到0.6版本，发现主程序无法启动，下附fasterwhispergui.log，命令nvidia-smi查看支持到cuda12.2
```
Traceback (most recent call last):
  File "D:\Program Files (x86)\FasterWhisperGUI\fasterwhispergui.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper_GUI\__init__.py", line 1, in <module faster_whisper_GUI>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Program Files (x86)\FasterWhisperGUI\whisperx\__init__.py", line 1, in <module whisperx>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Program Files (x86)\FasterWhisperGUI\whisperx\transcribe.py", line 7, in <module whisperx.transcribe>
  File "D:\Program Files (x86)\FasterWhisperGUI\torch\__init__.py", line 130, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\Program Files (x86)\FasterWhisperGUI\torch\lib\torch_cuda_cpp.dll" or one of its dependencies.
```

**Comment by CheshireCC** [comment]
卸载旧版，安装新版，程序不是更新包，是新版本安装包，无法更新安装

**Comment by Xuwznln** [comment]
感谢，卸载后重装已解决
