### ISSUE TITLE
The model cannot be loaded

### ISSUE THREAD

**Issue by wj2355021** [CheshireCC/faster-whisper-GUI#97]
![123](https://github.com/CheshireCC/faster-whisper-GUI/assets/32793452/5b44ac6a-4fb9-4a07-b3ee-94a89762d0cc)
    -model_size_or_path: tiny
    -device: auto
    -device_index: 0
    -compute_type: float32
    -cpu_threads: 0
    -num_workers: 0
    -download_root: C:/Users/wangj/.cache/huggingface/hub
    -local_files_only: True
    -use_v3_model: False
Traceback (most recent call last):
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper_GUI\modelLoad.py", line 41, in run
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper_GUI\modelLoad.py", line 80, in loadModel
  File "D:\Program Files (x86)\FasterWhisperGUI\faster_whisper\transcribe.py", line 133, in __init__
RuntimeError: File model.bin is incomplete: failed to read a value of size 4 at position 0

**Comment by CheshireCC** [comment]
The file was not downloaded completely. Try to download it again after deleting the cache file.
